// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.2
// - protoc             v5.27.3
// source: api/v1/core.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCoreAddLiveRoomDanmu = "/v1.Core/AddLiveRoomDanmu"
const OperationCoreDelLiveRoomDanmu = "/v1.Core/DelLiveRoomDanmu"

type CoreHTTPServer interface {
	// AddLiveRoomDanmu conn增删启停
	AddLiveRoomDanmu(context.Context, *AddLiveRoomDanmuReq) (*AddLiveRoomDanmuResp, error)
	DelLiveRoomDanmu(context.Context, *DelLiveRoomDanmuReq) (*DelLiveRoomDanmuResp, error)
}

func RegisterCoreHTTPServer(s *http.Server, srv CoreHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/core/add_live_room_danmu", _Core_AddLiveRoomDanmu0_HTTP_Handler(srv))
	r.POST("/api/v1/core/del_live_room_danmu", _Core_DelLiveRoomDanmu0_HTTP_Handler(srv))
}

func _Core_AddLiveRoomDanmu0_HTTP_Handler(srv CoreHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddLiveRoomDanmuReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCoreAddLiveRoomDanmu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddLiveRoomDanmu(ctx, req.(*AddLiveRoomDanmuReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddLiveRoomDanmuResp)
		return ctx.Result(200, reply)
	}
}

func _Core_DelLiveRoomDanmu0_HTTP_Handler(srv CoreHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DelLiveRoomDanmuReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCoreDelLiveRoomDanmu)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DelLiveRoomDanmu(ctx, req.(*DelLiveRoomDanmuReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DelLiveRoomDanmuResp)
		return ctx.Result(200, reply)
	}
}

type CoreHTTPClient interface {
	AddLiveRoomDanmu(ctx context.Context, req *AddLiveRoomDanmuReq, opts ...http.CallOption) (rsp *AddLiveRoomDanmuResp, err error)
	DelLiveRoomDanmu(ctx context.Context, req *DelLiveRoomDanmuReq, opts ...http.CallOption) (rsp *DelLiveRoomDanmuResp, err error)
}

type CoreHTTPClientImpl struct {
	cc *http.Client
}

func NewCoreHTTPClient(client *http.Client) CoreHTTPClient {
	return &CoreHTTPClientImpl{client}
}

func (c *CoreHTTPClientImpl) AddLiveRoomDanmu(ctx context.Context, in *AddLiveRoomDanmuReq, opts ...http.CallOption) (*AddLiveRoomDanmuResp, error) {
	var out AddLiveRoomDanmuResp
	pattern := "/api/v1/core/add_live_room_danmu"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCoreAddLiveRoomDanmu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CoreHTTPClientImpl) DelLiveRoomDanmu(ctx context.Context, in *DelLiveRoomDanmuReq, opts ...http.CallOption) (*DelLiveRoomDanmuResp, error) {
	var out DelLiveRoomDanmuResp
	pattern := "/api/v1/core/del_live_room_danmu"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCoreDelLiveRoomDanmu))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
