// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: api/v1/core.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLiveRoomDanmuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int64    `protobuf:"varint,1,opt,name=room_id,proto3" json:"room_id,omitempty"`
	RuleIdList []string `protobuf:"bytes,2,rep,name=rule_id_list,proto3" json:"rule_id_list,omitempty"`
}

func (x *AddLiveRoomDanmuReq) Reset() {
	*x = AddLiveRoomDanmuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLiveRoomDanmuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiveRoomDanmuReq) ProtoMessage() {}

func (x *AddLiveRoomDanmuReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiveRoomDanmuReq.ProtoReflect.Descriptor instead.
func (*AddLiveRoomDanmuReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *AddLiveRoomDanmuReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *AddLiveRoomDanmuReq) GetRuleIdList() []string {
	if x != nil {
		return x.RuleIdList
	}
	return nil
}

type AddLiveRoomDanmuResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddLiveRoomDanmuResp) Reset() {
	*x = AddLiveRoomDanmuResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLiveRoomDanmuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLiveRoomDanmuResp) ProtoMessage() {}

func (x *AddLiveRoomDanmuResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLiveRoomDanmuResp.ProtoReflect.Descriptor instead.
func (*AddLiveRoomDanmuResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{1}
}

type DelLiveRoomDanmuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,proto3" json:"room_id,omitempty"`
}

func (x *DelLiveRoomDanmuReq) Reset() {
	*x = DelLiveRoomDanmuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelLiveRoomDanmuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelLiveRoomDanmuReq) ProtoMessage() {}

func (x *DelLiveRoomDanmuReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelLiveRoomDanmuReq.ProtoReflect.Descriptor instead.
func (*DelLiveRoomDanmuReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *DelLiveRoomDanmuReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DelLiveRoomDanmuResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelLiveRoomDanmuResp) Reset() {
	*x = DelLiveRoomDanmuResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelLiveRoomDanmuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelLiveRoomDanmuResp) ProtoMessage() {}

func (x *DelLiveRoomDanmuResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelLiveRoomDanmuResp.ProtoReflect.Descriptor instead.
func (*DelLiveRoomDanmuResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{3}
}

type UpdateLiveRoomDanmuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId     int64    `protobuf:"varint,1,opt,name=room_id,proto3" json:"room_id,omitempty"`
	RuleIdList []string `protobuf:"bytes,2,rep,name=rule_id_list,proto3" json:"rule_id_list,omitempty"`
}

func (x *UpdateLiveRoomDanmuReq) Reset() {
	*x = UpdateLiveRoomDanmuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLiveRoomDanmuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveRoomDanmuReq) ProtoMessage() {}

func (x *UpdateLiveRoomDanmuReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveRoomDanmuReq.ProtoReflect.Descriptor instead.
func (*UpdateLiveRoomDanmuReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLiveRoomDanmuReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *UpdateLiveRoomDanmuReq) GetRuleIdList() []string {
	if x != nil {
		return x.RuleIdList
	}
	return nil
}

type UpdateLiveRoomDanmuResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateLiveRoomDanmuResp) Reset() {
	*x = UpdateLiveRoomDanmuResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLiveRoomDanmuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiveRoomDanmuResp) ProtoMessage() {}

func (x *UpdateLiveRoomDanmuResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiveRoomDanmuResp.ProtoReflect.Descriptor instead.
func (*UpdateLiveRoomDanmuResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{5}
}

type EnableLiveRoomDanmuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,proto3" json:"room_id,omitempty"`
}

func (x *EnableLiveRoomDanmuReq) Reset() {
	*x = EnableLiveRoomDanmuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableLiveRoomDanmuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableLiveRoomDanmuReq) ProtoMessage() {}

func (x *EnableLiveRoomDanmuReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableLiveRoomDanmuReq.ProtoReflect.Descriptor instead.
func (*EnableLiveRoomDanmuReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *EnableLiveRoomDanmuReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type EnableLiveRoomDanmuResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableLiveRoomDanmuResp) Reset() {
	*x = EnableLiveRoomDanmuResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableLiveRoomDanmuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableLiveRoomDanmuResp) ProtoMessage() {}

func (x *EnableLiveRoomDanmuResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableLiveRoomDanmuResp.ProtoReflect.Descriptor instead.
func (*EnableLiveRoomDanmuResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{7}
}

type DisableLiveRoomDanmuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,proto3" json:"room_id,omitempty"`
}

func (x *DisableLiveRoomDanmuReq) Reset() {
	*x = DisableLiveRoomDanmuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableLiveRoomDanmuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableLiveRoomDanmuReq) ProtoMessage() {}

func (x *DisableLiveRoomDanmuReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableLiveRoomDanmuReq.ProtoReflect.Descriptor instead.
func (*DisableLiveRoomDanmuReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *DisableLiveRoomDanmuReq) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type DisableLiveRoomDanmuResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableLiveRoomDanmuResp) Reset() {
	*x = DisableLiveRoomDanmuResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableLiveRoomDanmuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableLiveRoomDanmuResp) ProtoMessage() {}

func (x *DisableLiveRoomDanmuResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableLiveRoomDanmuResp.ProtoReflect.Descriptor instead.
func (*DisableLiveRoomDanmuResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{9}
}

type MatcherParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Param     string `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	BaseType  int64  `protobuf:"varint,2,opt,name=base_type,proto3" json:"base_type,omitempty"`
	MatchMode int64  `protobuf:"varint,3,opt,name=match_mode,proto3" json:"match_mode,omitempty"`
	Value     string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MatcherParam) Reset() {
	*x = MatcherParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatcherParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatcherParam) ProtoMessage() {}

func (x *MatcherParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatcherParam.ProtoReflect.Descriptor instead.
func (*MatcherParam) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *MatcherParam) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *MatcherParam) GetBaseType() int64 {
	if x != nil {
		return x.BaseType
	}
	return 0
}

func (x *MatcherParam) GetMatchMode() int64 {
	if x != nil {
		return x.MatchMode
	}
	return 0
}

func (x *MatcherParam) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DmType           int64           `protobuf:"varint,2,opt,name=dm_type,proto3" json:"dm_type,omitempty"`
	MatcherParamList []*MatcherParam `protobuf:"bytes,3,rep,name=matcher_param_list,proto3" json:"matcher_param_list,omitempty"`
	ActionIdList     []string        `protobuf:"bytes,4,rep,name=action_id_list,proto3" json:"action_id_list,omitempty"`
}

func (x *AddRuleReq) Reset() {
	*x = AddRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleReq) ProtoMessage() {}

func (x *AddRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleReq.ProtoReflect.Descriptor instead.
func (*AddRuleReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *AddRuleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddRuleReq) GetDmType() int64 {
	if x != nil {
		return x.DmType
	}
	return 0
}

func (x *AddRuleReq) GetMatcherParamList() []*MatcherParam {
	if x != nil {
		return x.MatcherParamList
	}
	return nil
}

func (x *AddRuleReq) GetActionIdList() []string {
	if x != nil {
		return x.ActionIdList
	}
	return nil
}

type AddRuleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRuleResp) Reset() {
	*x = AddRuleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRuleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleResp) ProtoMessage() {}

func (x *AddRuleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleResp.ProtoReflect.Descriptor instead.
func (*AddRuleResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{12}
}

type DelRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
}

func (x *DelRuleReq) Reset() {
	*x = DelRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRuleReq) ProtoMessage() {}

func (x *DelRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRuleReq.ProtoReflect.Descriptor instead.
func (*DelRuleReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{13}
}

func (x *DelRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type DelRuleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelRuleResp) Reset() {
	*x = DelRuleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRuleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRuleResp) ProtoMessage() {}

func (x *DelRuleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRuleResp.ProtoReflect.Descriptor instead.
func (*DelRuleResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{14}
}

type UpdateRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId           string          `protobuf:"bytes,1,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
	Name             string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DmType           int64           `protobuf:"varint,3,opt,name=dm_type,proto3" json:"dm_type,omitempty"`
	MatcherParamList []*MatcherParam `protobuf:"bytes,4,rep,name=matcher_param_list,proto3" json:"matcher_param_list,omitempty"`
	ActionIdList     []string        `protobuf:"bytes,5,rep,name=action_id_list,proto3" json:"action_id_list,omitempty"`
}

func (x *UpdateRuleReq) Reset() {
	*x = UpdateRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleReq) ProtoMessage() {}

func (x *UpdateRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleReq.ProtoReflect.Descriptor instead.
func (*UpdateRuleReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *UpdateRuleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRuleReq) GetDmType() int64 {
	if x != nil {
		return x.DmType
	}
	return 0
}

func (x *UpdateRuleReq) GetMatcherParamList() []*MatcherParam {
	if x != nil {
		return x.MatcherParamList
	}
	return nil
}

func (x *UpdateRuleReq) GetActionIdList() []string {
	if x != nil {
		return x.ActionIdList
	}
	return nil
}

type UpdateRuleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRuleResp) Reset() {
	*x = UpdateRuleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRuleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleResp) ProtoMessage() {}

func (x *UpdateRuleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleResp.ProtoReflect.Descriptor instead.
func (*UpdateRuleResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{16}
}

type EnableRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
}

func (x *EnableRuleReq) Reset() {
	*x = EnableRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRuleReq) ProtoMessage() {}

func (x *EnableRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRuleReq.ProtoReflect.Descriptor instead.
func (*EnableRuleReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{17}
}

func (x *EnableRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type EnableRuleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableRuleResp) Reset() {
	*x = EnableRuleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableRuleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRuleResp) ProtoMessage() {}

func (x *EnableRuleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRuleResp.ProtoReflect.Descriptor instead.
func (*EnableRuleResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{18}
}

type DisableRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
}

func (x *DisableRuleReq) Reset() {
	*x = DisableRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRuleReq) ProtoMessage() {}

func (x *DisableRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRuleReq.ProtoReflect.Descriptor instead.
func (*DisableRuleReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{19}
}

func (x *DisableRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type DisableRuleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableRuleResp) Reset() {
	*x = DisableRuleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableRuleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRuleResp) ProtoMessage() {}

func (x *DisableRuleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRuleResp.ProtoReflect.Descriptor instead.
func (*DisableRuleResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{20}
}

type PreCheckDelRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
}

func (x *PreCheckDelRuleReq) Reset() {
	*x = PreCheckDelRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreCheckDelRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckDelRuleReq) ProtoMessage() {}

func (x *PreCheckDelRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckDelRuleReq.ProtoReflect.Descriptor instead.
func (*PreCheckDelRuleReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{21}
}

func (x *PreCheckDelRuleReq) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type PreCheckDelRuleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomInfoList []*RoomInfo `protobuf:"bytes,1,rep,name=room_info_list,proto3" json:"room_info_list,omitempty"`
}

func (x *PreCheckDelRuleResp) Reset() {
	*x = PreCheckDelRuleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreCheckDelRuleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckDelRuleResp) ProtoMessage() {}

func (x *PreCheckDelRuleResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckDelRuleResp.ProtoReflect.Descriptor instead.
func (*PreCheckDelRuleResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{22}
}

func (x *PreCheckDelRuleResp) GetRoomInfoList() []*RoomInfo {
	if x != nil {
		return x.RoomInfoList
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64  `protobuf:"varint,1,opt,name=room_id,proto3" json:"room_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Face   string `protobuf:"bytes,3,opt,name=face,proto3" json:"face,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{23}
}

func (x *RoomInfo) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetFace() string {
	if x != nil {
		return x.Face
	}
	return ""
}

type AddActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ActionType int64             `protobuf:"varint,2,opt,name=action_type,proto3" json:"action_type,omitempty"`
	Extra      map[string]string `protobuf:"bytes,3,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AddActionReq) Reset() {
	*x = AddActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionReq) ProtoMessage() {}

func (x *AddActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionReq.ProtoReflect.Descriptor instead.
func (*AddActionReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{24}
}

func (x *AddActionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddActionReq) GetActionType() int64 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *AddActionReq) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type AddActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddActionResp) Reset() {
	*x = AddActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionResp) ProtoMessage() {}

func (x *AddActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionResp.ProtoReflect.Descriptor instead.
func (*AddActionResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{25}
}

type DelActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId string `protobuf:"bytes,1,opt,name=action_id,proto3" json:"action_id,omitempty"`
}

func (x *DelActionReq) Reset() {
	*x = DelActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelActionReq) ProtoMessage() {}

func (x *DelActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelActionReq.ProtoReflect.Descriptor instead.
func (*DelActionReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{26}
}

func (x *DelActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type DelActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelActionResp) Reset() {
	*x = DelActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelActionResp) ProtoMessage() {}

func (x *DelActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelActionResp.ProtoReflect.Descriptor instead.
func (*DelActionResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{27}
}

type UpdateActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId   string            `protobuf:"bytes,1,opt,name=action_id,proto3" json:"action_id,omitempty"`
	Name       string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ActionType int64             `protobuf:"varint,3,opt,name=action_type,proto3" json:"action_type,omitempty"`
	Extra      map[string]string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UpdateActionReq) Reset() {
	*x = UpdateActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionReq) ProtoMessage() {}

func (x *UpdateActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionReq.ProtoReflect.Descriptor instead.
func (*UpdateActionReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *UpdateActionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateActionReq) GetActionType() int64 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

func (x *UpdateActionReq) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type UpdateActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateActionResp) Reset() {
	*x = UpdateActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionResp) ProtoMessage() {}

func (x *UpdateActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionResp.ProtoReflect.Descriptor instead.
func (*UpdateActionResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{29}
}

type EnableActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId string `protobuf:"bytes,1,opt,name=action_id,proto3" json:"action_id,omitempty"`
}

func (x *EnableActionReq) Reset() {
	*x = EnableActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableActionReq) ProtoMessage() {}

func (x *EnableActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableActionReq.ProtoReflect.Descriptor instead.
func (*EnableActionReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{30}
}

func (x *EnableActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type EnableActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableActionResp) Reset() {
	*x = EnableActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableActionResp) ProtoMessage() {}

func (x *EnableActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableActionResp.ProtoReflect.Descriptor instead.
func (*EnableActionResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{31}
}

type DisableActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId string `protobuf:"bytes,1,opt,name=action_id,proto3" json:"action_id,omitempty"`
}

func (x *DisableActionReq) Reset() {
	*x = DisableActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableActionReq) ProtoMessage() {}

func (x *DisableActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableActionReq.ProtoReflect.Descriptor instead.
func (*DisableActionReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{32}
}

func (x *DisableActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type DisableActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableActionResp) Reset() {
	*x = DisableActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableActionResp) ProtoMessage() {}

func (x *DisableActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableActionResp.ProtoReflect.Descriptor instead.
func (*DisableActionResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{33}
}

type PreCheckDelActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionId string `protobuf:"bytes,1,opt,name=action_id,proto3" json:"action_id,omitempty"`
}

func (x *PreCheckDelActionReq) Reset() {
	*x = PreCheckDelActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreCheckDelActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckDelActionReq) ProtoMessage() {}

func (x *PreCheckDelActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckDelActionReq.ProtoReflect.Descriptor instead.
func (*PreCheckDelActionReq) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{34}
}

func (x *PreCheckDelActionReq) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type PreCheckDelActionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleInfoList []*RuleInfo `protobuf:"bytes,1,rep,name=rule_info_list,proto3" json:"rule_info_list,omitempty"`
}

func (x *PreCheckDelActionResp) Reset() {
	*x = PreCheckDelActionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreCheckDelActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckDelActionResp) ProtoMessage() {}

func (x *PreCheckDelActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckDelActionResp.ProtoReflect.Descriptor instead.
func (*PreCheckDelActionResp) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{35}
}

func (x *PreCheckDelActionResp) GetRuleInfoList() []*RuleInfo {
	if x != nil {
		return x.RuleInfoList
	}
	return nil
}

type RuleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,proto3" json:"rule_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RuleInfo) Reset() {
	*x = RuleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_core_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleInfo) ProtoMessage() {}

func (x *RuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_core_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleInfo.ProtoReflect.Descriptor instead.
func (*RuleInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_core_proto_rawDescGZIP(), []int{36}
}

func (x *RuleInfo) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_v1_core_proto protoreflect.FileDescriptor

var file_api_v1_core_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x76, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x75,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x56, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e,
	0x6d, 0x75, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x32,
	0x0a, 0x16, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x33, 0x0a,
	0x17, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x78,
	0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x52, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x22,
	0x0d, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x26,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc1, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x40, 0x0a, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x12, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x29, 0x0a, 0x0d, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x75,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x75, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x72, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x50, 0x72, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34,
	0x0a, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x61,
	0x63, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0f, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2c, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd5, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x34,
	0x0a, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x12,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x2f, 0x0a, 0x0f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x30, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x34,
	0x0a, 0x14, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a,
	0x0e, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xdf, 0x0d,
	0x0a, 0x04, 0x43, 0x6f, 0x72, 0x65, 0x12, 0x72, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x64, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x76, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2b, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x25, 0x22, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x61, 0x64, 0x64, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x3a, 0x01, 0x2a, 0x12, 0x72, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x12, 0x17,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44,
	0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25, 0x22, 0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x65, 0x6c, 0x5f, 0x6c, 0x69, 0x76, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x3a, 0x01, 0x2a, 0x12, 0x7e,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x6e, 0x6d, 0x75, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x22, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x76, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x3a, 0x01, 0x2a, 0x12, 0x7e,
	0x0a, 0x13, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x44, 0x61, 0x6e, 0x6d, 0x75, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65,
	0x71, 0x1a, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x22, 0x23, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x76, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x6e, 0x6d, 0x75, 0x3a, 0x01, 0x2a, 0x12, 0x82,
	0x01, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d,
	0x75, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x6e, 0x6d, 0x75, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x22, 0x24, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6c, 0x69, 0x76, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x64, 0x61, 0x6e, 0x6d, 0x75,
	0x3a, 0x01, 0x2a, 0x12, 0x4c, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0e,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x64, 0x64, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x3a, 0x01,
	0x2a, 0x12, 0x4c, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x72, 0x65, 0x2f, 0x64, 0x65, 0x6c, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x3a, 0x01, 0x2a, 0x12,
	0x58, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x11, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x18, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x58, 0x0a, 0x0a, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65,
	0x3a, 0x01, 0x2a, 0x12, 0x5c, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x75,
	0x6c, 0x65, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x24, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1e, 0x22, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x3a, 0x01,
	0x2a, 0x12, 0x6e, 0x0a, 0x0f, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c,
	0x52, 0x75, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x52, 0x75, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x22, 0x1f, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x5f,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x6c, 0x5f, 0x72, 0x75, 0x6c, 0x65, 0x3a, 0x01,
	0x2a, 0x12, 0x54, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x22, 0x17, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x64, 0x64, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x54, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1c, 0x22, 0x17, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x64, 0x65, 0x6c, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x60, 0x0a,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f,
	0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12,
	0x60, 0x0a, 0x0c, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x13, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1f, 0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65,
	0x2f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01,
	0x2a, 0x12, 0x64, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x22, 0x1b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x76, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x65, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x22, 0x21, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x72, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x5f, 0x64, 0x65, 0x6c, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x42,
	0x14, 0x5a, 0x12, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2d, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_core_proto_rawDescOnce sync.Once
	file_api_v1_core_proto_rawDescData = file_api_v1_core_proto_rawDesc
)

func file_api_v1_core_proto_rawDescGZIP() []byte {
	file_api_v1_core_proto_rawDescOnce.Do(func() {
		file_api_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_core_proto_rawDescData)
	})
	return file_api_v1_core_proto_rawDescData
}

var file_api_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_api_v1_core_proto_goTypes = []interface{}{
	(*AddLiveRoomDanmuReq)(nil),      // 0: v1.AddLiveRoomDanmuReq
	(*AddLiveRoomDanmuResp)(nil),     // 1: v1.AddLiveRoomDanmuResp
	(*DelLiveRoomDanmuReq)(nil),      // 2: v1.DelLiveRoomDanmuReq
	(*DelLiveRoomDanmuResp)(nil),     // 3: v1.DelLiveRoomDanmuResp
	(*UpdateLiveRoomDanmuReq)(nil),   // 4: v1.UpdateLiveRoomDanmuReq
	(*UpdateLiveRoomDanmuResp)(nil),  // 5: v1.UpdateLiveRoomDanmuResp
	(*EnableLiveRoomDanmuReq)(nil),   // 6: v1.EnableLiveRoomDanmuReq
	(*EnableLiveRoomDanmuResp)(nil),  // 7: v1.EnableLiveRoomDanmuResp
	(*DisableLiveRoomDanmuReq)(nil),  // 8: v1.DisableLiveRoomDanmuReq
	(*DisableLiveRoomDanmuResp)(nil), // 9: v1.DisableLiveRoomDanmuResp
	(*MatcherParam)(nil),             // 10: v1.MatcherParam
	(*AddRuleReq)(nil),               // 11: v1.AddRuleReq
	(*AddRuleResp)(nil),              // 12: v1.AddRuleResp
	(*DelRuleReq)(nil),               // 13: v1.DelRuleReq
	(*DelRuleResp)(nil),              // 14: v1.DelRuleResp
	(*UpdateRuleReq)(nil),            // 15: v1.UpdateRuleReq
	(*UpdateRuleResp)(nil),           // 16: v1.UpdateRuleResp
	(*EnableRuleReq)(nil),            // 17: v1.EnableRuleReq
	(*EnableRuleResp)(nil),           // 18: v1.EnableRuleResp
	(*DisableRuleReq)(nil),           // 19: v1.DisableRuleReq
	(*DisableRuleResp)(nil),          // 20: v1.DisableRuleResp
	(*PreCheckDelRuleReq)(nil),       // 21: v1.PreCheckDelRuleReq
	(*PreCheckDelRuleResp)(nil),      // 22: v1.PreCheckDelRuleResp
	(*RoomInfo)(nil),                 // 23: v1.RoomInfo
	(*AddActionReq)(nil),             // 24: v1.AddActionReq
	(*AddActionResp)(nil),            // 25: v1.AddActionResp
	(*DelActionReq)(nil),             // 26: v1.DelActionReq
	(*DelActionResp)(nil),            // 27: v1.DelActionResp
	(*UpdateActionReq)(nil),          // 28: v1.UpdateActionReq
	(*UpdateActionResp)(nil),         // 29: v1.UpdateActionResp
	(*EnableActionReq)(nil),          // 30: v1.EnableActionReq
	(*EnableActionResp)(nil),         // 31: v1.EnableActionResp
	(*DisableActionReq)(nil),         // 32: v1.DisableActionReq
	(*DisableActionResp)(nil),        // 33: v1.DisableActionResp
	(*PreCheckDelActionReq)(nil),     // 34: v1.PreCheckDelActionReq
	(*PreCheckDelActionResp)(nil),    // 35: v1.PreCheckDelActionResp
	(*RuleInfo)(nil),                 // 36: v1.RuleInfo
	nil,                              // 37: v1.AddActionReq.ExtraEntry
	nil,                              // 38: v1.UpdateActionReq.ExtraEntry
}
var file_api_v1_core_proto_depIdxs = []int32{
	10, // 0: v1.AddRuleReq.matcher_param_list:type_name -> v1.MatcherParam
	10, // 1: v1.UpdateRuleReq.matcher_param_list:type_name -> v1.MatcherParam
	23, // 2: v1.PreCheckDelRuleResp.room_info_list:type_name -> v1.RoomInfo
	37, // 3: v1.AddActionReq.extra:type_name -> v1.AddActionReq.ExtraEntry
	38, // 4: v1.UpdateActionReq.extra:type_name -> v1.UpdateActionReq.ExtraEntry
	36, // 5: v1.PreCheckDelActionResp.rule_info_list:type_name -> v1.RuleInfo
	0,  // 6: v1.Core.AddLiveRoomDanmu:input_type -> v1.AddLiveRoomDanmuReq
	2,  // 7: v1.Core.DelLiveRoomDanmu:input_type -> v1.DelLiveRoomDanmuReq
	4,  // 8: v1.Core.UpdateLiveRoomDanmu:input_type -> v1.UpdateLiveRoomDanmuReq
	6,  // 9: v1.Core.EnableLiveRoomDanmu:input_type -> v1.EnableLiveRoomDanmuReq
	8,  // 10: v1.Core.DisableLiveRoomDanmu:input_type -> v1.DisableLiveRoomDanmuReq
	11, // 11: v1.Core.AddRule:input_type -> v1.AddRuleReq
	13, // 12: v1.Core.DelRule:input_type -> v1.DelRuleReq
	15, // 13: v1.Core.UpdateRule:input_type -> v1.UpdateRuleReq
	17, // 14: v1.Core.EnableRule:input_type -> v1.EnableRuleReq
	19, // 15: v1.Core.DisableRule:input_type -> v1.DisableRuleReq
	21, // 16: v1.Core.PreCheckDelRule:input_type -> v1.PreCheckDelRuleReq
	24, // 17: v1.Core.AddAction:input_type -> v1.AddActionReq
	26, // 18: v1.Core.DelAction:input_type -> v1.DelActionReq
	28, // 19: v1.Core.UpdateAction:input_type -> v1.UpdateActionReq
	30, // 20: v1.Core.EnableAction:input_type -> v1.EnableActionReq
	32, // 21: v1.Core.DisableAction:input_type -> v1.DisableActionReq
	34, // 22: v1.Core.PreCheckDelAction:input_type -> v1.PreCheckDelActionReq
	1,  // 23: v1.Core.AddLiveRoomDanmu:output_type -> v1.AddLiveRoomDanmuResp
	3,  // 24: v1.Core.DelLiveRoomDanmu:output_type -> v1.DelLiveRoomDanmuResp
	5,  // 25: v1.Core.UpdateLiveRoomDanmu:output_type -> v1.UpdateLiveRoomDanmuResp
	7,  // 26: v1.Core.EnableLiveRoomDanmu:output_type -> v1.EnableLiveRoomDanmuResp
	9,  // 27: v1.Core.DisableLiveRoomDanmu:output_type -> v1.DisableLiveRoomDanmuResp
	12, // 28: v1.Core.AddRule:output_type -> v1.AddRuleResp
	14, // 29: v1.Core.DelRule:output_type -> v1.DelRuleResp
	16, // 30: v1.Core.UpdateRule:output_type -> v1.UpdateRuleResp
	18, // 31: v1.Core.EnableRule:output_type -> v1.EnableRuleResp
	20, // 32: v1.Core.DisableRule:output_type -> v1.DisableRuleResp
	22, // 33: v1.Core.PreCheckDelRule:output_type -> v1.PreCheckDelRuleResp
	25, // 34: v1.Core.AddAction:output_type -> v1.AddActionResp
	27, // 35: v1.Core.DelAction:output_type -> v1.DelActionResp
	29, // 36: v1.Core.UpdateAction:output_type -> v1.UpdateActionResp
	31, // 37: v1.Core.EnableAction:output_type -> v1.EnableActionResp
	33, // 38: v1.Core.DisableAction:output_type -> v1.DisableActionResp
	35, // 39: v1.Core.PreCheckDelAction:output_type -> v1.PreCheckDelActionResp
	23, // [23:40] is the sub-list for method output_type
	6,  // [6:23] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_core_proto_init() }
func file_api_v1_core_proto_init() {
	if File_api_v1_core_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_core_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLiveRoomDanmuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLiveRoomDanmuResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelLiveRoomDanmuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelLiveRoomDanmuResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLiveRoomDanmuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLiveRoomDanmuResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableLiveRoomDanmuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableLiveRoomDanmuResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableLiveRoomDanmuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableLiveRoomDanmuResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatcherParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRuleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRuleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRuleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableRuleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableRuleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreCheckDelRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreCheckDelRuleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreCheckDelActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreCheckDelActionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_core_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_core_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_core_proto_goTypes,
		DependencyIndexes: file_api_v1_core_proto_depIdxs,
		MessageInfos:      file_api_v1_core_proto_msgTypes,
	}.Build()
	File_api_v1_core_proto = out.File
	file_api_v1_core_proto_rawDesc = nil
	file_api_v1_core_proto_goTypes = nil
	file_api_v1_core_proto_depIdxs = nil
}
