// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.1
// - protoc             v3.14.0
// source: api/v1/setting.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSettingGetConfig = "/v1.Setting/GetConfig"
const OperationSettingSetConfig = "/v1.Setting/SetConfig"

type SettingHTTPServer interface {
	GetConfig(context.Context, *GetConfigReq) (*GetConfigResp, error)
	SetConfig(context.Context, *SetConfigReq) (*SetConfigResp, error)
}

func RegisterSettingHTTPServer(s *http.Server, srv SettingHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/setting/get_config", _Setting_GetConfig0_HTTP_Handler(srv))
	r.POST("/api/v1/setting/set_config", _Setting_SetConfig0_HTTP_Handler(srv))
}

func _Setting_GetConfig0_HTTP_Handler(srv SettingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConfigReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSettingGetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConfig(ctx, req.(*GetConfigReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetConfigResp)
		return ctx.Result(200, reply)
	}
}

func _Setting_SetConfig0_HTTP_Handler(srv SettingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetConfigReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSettingSetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetConfig(ctx, req.(*SetConfigReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetConfigResp)
		return ctx.Result(200, reply)
	}
}

type SettingHTTPClient interface {
	GetConfig(ctx context.Context, req *GetConfigReq, opts ...http.CallOption) (rsp *GetConfigResp, err error)
	SetConfig(ctx context.Context, req *SetConfigReq, opts ...http.CallOption) (rsp *SetConfigResp, err error)
}

type SettingHTTPClientImpl struct {
	cc *http.Client
}

func NewSettingHTTPClient(client *http.Client) SettingHTTPClient {
	return &SettingHTTPClientImpl{client}
}

func (c *SettingHTTPClientImpl) GetConfig(ctx context.Context, in *GetConfigReq, opts ...http.CallOption) (*GetConfigResp, error) {
	var out GetConfigResp
	pattern := "/api/v1/setting/get_config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSettingGetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SettingHTTPClientImpl) SetConfig(ctx context.Context, in *SetConfigReq, opts ...http.CallOption) (*SetConfigResp, error) {
	var out SetConfigResp
	pattern := "/api/v1/setting/set_config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSettingSetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
